### ISSUE TITLE
json parser: improve consistency when creating carbon file from json array

### ISSUE THREAD

**Issue by Jasper-Ben** [jaksonlabs/jakson#3]
Currently when converting any non-array JSON element there the converted data is wrapped into an array within carbon. For example the JSON file `{}` is converted into the CARBON file `[{}]`.
However, when dealing with an array JSON element, this step is skipped.
This means that the JSON file `[{}]` will result in the same CARBON file as the example above.

This is bad for at least two reasons:
1. The original JSON file cannot be recreated from an existing CARBON file
2.  Issues when trying to evaluate a JSON array against a schema file

I therefore suggest we also wrap JSON array elements into an additional array layer, resulting in:
JSON `[{}]` -> CARBON `[[{}]]`, JSON `{}` -> CARBON `[{}]`

**Comment by pinnecke** [comment]
Hi Jasper, as discussed in person, thanks for your issue description here. What you describe is true from a certain point of view (to quote Obi-Wan). 

The latest json converter (`json_from(record)`) will convert the following input JSON files as follows (don't showing how it is internally stored in Carbon):

- JSON in `[]`, JSON out `[]`
- JSON in `{}`, JSON out `{}`
- JSON in `{"_": []}`, JSON out `{"_": []}`
and 
- JSON in `[{}]` to JSON out `{}`

The last in the list from above is what you are concerned with. The reason for this is that JSON and Carbon have a different semantic in how to understand list types and non-list types. While  in JSON (although not specified by the standard), the common sense is that an element (say `x`) is _not_ equal to a list in which `x` occurs exclusively (i.e., `[x]`). 

In Carbon, that's different: any element `x` is equal to a list in which this element occurs exclusively, i.e., in Carbon `equals(x, [x])` holds while in JSON that's typically not the case. The reason for this design decision in Carbon is that Carbon does not center around list types _and_ non-list types as JSON, but list types only. This means, any non-list element is a list element where this list has exactly one element, the element by itself. Please note that this behavior is from a logical perspective only, and not implemented in that way straight forward. 

For example, the JSON input `{"_": 1}` is stored internally (assuming `nokey`as primary key) as `[?][{[1][_][c][1]}]` and not as `[?][{[1][_][c][[][1][]]}]`(note here the `[[]...[]]`). That is for size-efficiency reasons. However, when working with `"_": 1` it shall behaveslike `"_": [1]`.

Regarding you concerns. 

The first (the original JSON cannot be recreated) is true and cannot be fixed, since there is information loss from JSON over Carbon back to JSON due to the semantic described above. However, this isn't a problem unless for very special cases, and may be fixed in future by user empowerment (e.g., a set of config options and patterns that tells the JSON converter when to wrap or when to unwrap single-item lists in Carbon). 

The second (issues when evaluating a JSON array against a schema) is also true, but this is not what you should do. You have to evaluate a Carbon array against a schema, and with this, the semantics are completely clearly defined. A consequence is, that JSON-centered approaches (like JSON schema) cannot be implemented straight forward for Carbon but must be slightly modified to consider Carbon semantics rather than JSON semantics.
